Thx8411 sv305 2
indilib/indi-3rdparty pull request #194
Opened 2020-08-19 23:04 UTC by thx8411

Hello,

This is the new  SV305 driver, using the last SVBONY SDK.
I almost rewrote everything

Changes :
- armv6, armv7 and armv8 support added
- no more magic numbers nor hard coded settings
- should also support the SV305 PRO (but not tested yet)
- better live view
- switched from software ROI to hardware ROI
- full access to camera settings

Known issues : 
- initial gain setting sometime fails (SDK issue ?)

Limitations :
- no binning nor sub framing in live view
- no exposure abort

Best regards,

Blaise

2020-08-19 23:19 UTC, knro requested changes
Few changes required.

2020-08-19 23:19 UTC, knro commented on cmake_modules/FindSV305.cmake
> +  find_library(SV305_LIBRARIES NAMES libSVBCameraSDK.so
libSVBCameraSDK.so --> SVBCameraSDK

2020-08-19 23:19 UTC, knro commented on debian/indi-sv305/changelog
> +indi-sv305 (1.1.1) bionic; urgency=low
Better make the version 1.2 to be consistent with previous versions.

2020-08-19 23:19 UTC, knro commented on debian/indi-sv305/control
> +Architecture: i386 amd64 armel armhf arm64
probably safe to drop armel since there are no builds for this in the PPA AFAIK.

2020-08-19 23:19 UTC, knro commented on debian/libsv305/control
> +Architecture: i386 amd64 armel armhf arm64
same note on armel as before.

2020-08-20 12:30 UTC, thx8411 commented
Thanks for your review.

Requested changes done.

2020-08-20 13:17 UTC, merged