Add driver for Orion StarShoot G3 cameras
indilib/indi-3rdparty pull request #430
Opened 2021-08-07 01:55 UTC by bgilsrud

This commit adds the indi_orion_ssg3_ccd driver which supports the Orion
StarShoot G3 cameras (color and mono).

fixes #125

2021-08-07 07:30 UTC, knro commented
Thank you! For new drivers, we should probably adopt the new INDI property standards.

So instead of:

INumber GainN[1];
INumberVectorProperty GainNP;

We use:

INDI::Number GainNP[1];

Also, we have better timers now than the old method (both INDI::Timer and INDI::ElapsedTimer), thanks to @pawel-soja work. So these are preferred as well. [INDI ASI driver](https://github.com/indilib/indi-3rdparty/tree/master/indi-asi) was updated to these new standards so it's worth taking a look there.

2021-08-11 09:10 UTC, knro requested changes
Great work in the migration process, Bravo!

Just small changes required which normal given this is your first driver in the new INDI API.

2021-08-11 09:10 UTC, knro commented on indi-orion-ssg3/orion_ssg3_ccd.cpp
> +    LOG_DEBUG("Starting exposure");
Just beware that if users take very short successive exposures, this can swell up the log.

2021-08-11 09:10 UTC, knro commented on indi-orion-ssg3/orion_ssg3_ccd.cpp
> +        timeleft = CalcTimeLeft();
No need to use this function, use INDI::ElapsedTimer which is better than this method.

2021-08-11 09:10 UTC, knro commented on indi-orion-ssg3/orion_ssg3_ccd.cpp
> +    sz = PrimaryCCD.getFrameBufferSize();
just define it here, i.e.
uint32_t sz = PrimaryCCD.getFrameBufferSize()

2021-08-11 09:10 UTC, knro commented on indi-orion-ssg3/orion_ssg3_ccd.cpp
> +            LOGF_DEBUG("Read temperature: %f\n", temp);
No new for newline \n

2021-08-11 09:10 UTC, knro commented on indi-orion-ssg3/orion_ssg3_ccd.cpp
> +    NSTimer.callOnTimeout(std::bind(&SSG3CCD::stopNSGuide, this));
You can call this once in the constructor, no need to re-bind for each guide call.

2021-08-11 09:10 UTC, knro commented on indi-orion-ssg3/orion_ssg3_ccd.cpp
> +    }
since rc is not used, you can simplify this:

if (orion_ssg3_st4(&ssg3, SSG3_GUIDE_SOUTH, ms))
   return IPS_ALERT;

2021-08-12 02:13 UTC, bgilsrud commented on indi-orion-ssg3/orion_ssg3_ccd.cpp
> +        loadConfig(true, OffsetNP.getName());
I think you're suggesting that I condition the loadConfig on the property not being empty? I looked at the ASI driver and copied what was done there so let me know if that's not correct.

2021-08-12 10:55 UTC, knro commented on indi-orion-ssg3/orion_ssg3_ccd.cpp
> +        loadConfig(true, OffsetNP.getName());
Just skip the loadConfig all together since clients will just call loadConfig once everything is up.

2021-08-12 12:39 UTC, knro commented
Great! Driver side is done, now we need debian files. These should be easy to do, just copy over indi-asi or any other driver and modify accordingly.

2021-08-12 13:10 UTC, bgilsrud commented
I added the debian files and was able to build the packages.

2021-08-12 13:23 UTC, knro commented on debian/indi-orion-ssg3/copyright
> +    Copyright 2014 Chrstian Pellegrin <<chripell AT gmail DOT com>
shouldn't this be you?

2021-08-12 14:58 UTC, knro requested changes
Please clarify the liborion-ssg3 dependency.

2021-08-12 17:33 UTC, bgilsrud commented on debian/indi-orion-ssg3/copyright
> +    Copyright 2014 Chrstian Pellegrin <<chripell AT gmail DOT com>
fixed

2021-08-12 17:34 UTC, bgilsrud commented
I actually installed the deb packages this time :smile:

2021-08-12 21:41 UTC, merged

2021-08-12 21:45 UTC, bgilsrud commented
Thanks @knro !

2021-08-13 15:27 UTC, knro commented
Absolutely! Can you please submit an entry for the documentation on INDI Website? Do you already have access? Same format as the other driver documentation.

2021-08-13 18:55 UTC, bgilsrud commented
I would be happy to do that, but I don't believe that I have access.

2021-08-13 19:10 UTC, knro commented
You can go ahead and [add a new listing](https://indilib.org/devices/add.html). Regarding the images, maybe you can attach in a zip file and I'll upload later.

2021-11-15 23:02 UTC, Manu4810 commented
Dear Ben, I get back to you about the Brightstar Mammut Lyuba which hopefully can be controlled using your latest indi_orion_ssg3_ccd driver.
After adding the above driver (package installed from Raspbian / Astroberry package manager), I start the INDI server, and while connecting the camera I have the following error message from INDI client:

[ERROR] Unable to connect to Orion StarShoot G3: operation not permitted.

The VID and PID of the camera are the following (not sure you got this info when you asked for it back in July): 
Bus 004 Device 004: ID 07ee:0501 Torex Retail (formerly Logware) AVR32 UC3 USB DEVICE
Any clues ? I guess this is something pretty obvious, but I never came across such message, and other cameras I have (more mainstream such as QHY and ZWO)  can connect plug&play.
Thanks a lot !
Emmanuel